/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedManageCoursesRouteImport } from './routes/_authenticated/manage-courses'
import { Route as AuthenticatedMyLearningRouteImport } from './routes/_authenticated/my-learning'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedAssessmentsIdRouteImport } from './routes/_authenticated/assessments.$id'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageCoursesRoute =
  AuthenticatedManageCoursesRouteImport.update({
    id: '/manage-courses',
    path: '/manage-courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyLearningRoute = AuthenticatedMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsIdRoute =
  AuthenticatedAssessmentsIdRouteImport.update({
    id: '/assessments/$id',
    path: '/assessments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/courses/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manage-courses': typeof AuthenticatedManageCoursesRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manage-courses': typeof AuthenticatedManageCoursesRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/manage-courses': typeof AuthenticatedManageCoursesRoute
  '/_authenticated/my-learning': typeof AuthenticatedMyLearningRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/_authenticated/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/verify'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/certificates'
    | '/dashboard'
    | '/manage-courses'
    | '/my-learning'
    | '/profile'
    | '/users'
    | '/assessments/$id'
    | '/courses/$slug'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/verify'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/certificates'
    | '/dashboard'
    | '/manage-courses'
    | '/my-learning'
    | '/profile'
    | '/users'
    | '/assessments/$id'
    | '/courses/$slug'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/verify'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/assistant'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/manage-courses'
    | '/_authenticated/my-learning'
    | '/_authenticated/profile'
    | '/_authenticated/users'
    | '/_authenticated/assessments/$id'
    | '/_authenticated/courses/$slug'
    | '/_authenticated/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-courses': {
      id: '/_authenticated/manage-courses'
      path: '/manage-courses'
      fullPath: '/manage-courses'
      preLoaderRoute: typeof AuthenticatedManageCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-learning': {
      id: '/_authenticated/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AuthenticatedMyLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$id': {
      id: '/_authenticated/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$slug': {
      id: '/_authenticated/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedManageCoursesRoute: typeof AuthenticatedManageCoursesRoute
  AuthenticatedMyLearningRoute: typeof AuthenticatedMyLearningRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAssessmentsIdRoute: typeof AuthenticatedAssessmentsIdRoute
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedManageCoursesRoute: AuthenticatedManageCoursesRoute,
  AuthenticatedMyLearningRoute: AuthenticatedMyLearningRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAssessmentsIdRoute: AuthenticatedAssessmentsIdRoute,
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
